# Generated by Django 5.0.2 on 2024-02-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alpha_2", models.CharField(max_length=2)),
                ("alpha_3", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
