# Generated by Django 5.0.2 on 2024-02-27 15:58
from csv import DictReader

from django.db import migrations


def load_data(apps, schema_editor):
    Country = apps.get_model('one_country_a_day', 'Country')

    with open('./one_country_a_day/migrations/countries.csv', newline='') as csvfile:
        reader = DictReader(csvfile)
        for row in reader:
            Country.objects.create(alpha_2=row['alpha2'], alpha_3=row['alpha3'], name=row['name'])


class Migration(migrations.Migration):

    dependencies = [('one_country_a_day', '0001_initial')]

    operations = [
        migrations.RunPython(load_data),
    ]
