# Generated by Django 5.0.2 on 2024-03-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("one_country_a_day", "0002_preload_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.TextField()),
                ("flag", models.TextField()),
                ("cuisine", models.TextField()),
                ("dish", models.TextField()),
                ("area", models.TextField()),
                ("population", models.TextField()),
                ("fauna", models.TextField()),
                ("food_production", models.TextField()),
                ("borders", models.TextField()),
            ],
        ),
    ]
