# Generated by Django 5.0.2 on 2024-03-29 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("one_country_a_day", "0003_countrydata"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrydata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
